### ISSUE TITLE
syntax issue / question

### ISSUE THREAD

**Issue by mabrafoo** [funkandwagnalls/ranger#6]
Great presentation at bsides charm!  
I am trying to figure out how to run a single powersploit ps1 file.

ranger -t 192.168.22.200 -u username -p password --executor -x Get-GPPPassword.ps1 
[!] You must provide at least the name tool to be injected into memory and the cmdlet name to be executed
Obviously I am missing something the command needs for this to work.

**Comment by funkandwagnalls** [comment]
Thanks for the compliment and coming to the talk.  You need to pass the arguments for the script through a -f.  We have not tested any scripts, which do not require arguments yet.   Test it with a -f "" if no cmdlet or function is required.
