### ISSUE TITLE
video from bsides charm

### ISSUE THREAD

**Issue by mabrafooMSFT** [funkandwagnalls/ranger#7]
It would be great to see the bsides charm presentation again.  Any idea if the video exists anywhere?  I have not been able to find it using bing.com

**Comment by funkandwagnalls** [comment]
We are still waiting on BSides.  Feel free to poke them ;)

**Comment by funkandwagnalls** [comment]
https://www.youtube.com/playlist?list=PL0YXeUocWA4NAGPmYdKNmQEh8H6iL_4Ik

**Comment by funkandwagnalls** [comment]
Good Day,

It has been recently added to YouTube!  Thanks for the interest.
https://youtu.be/HrXTrPzdR2Q?list=PL0YXeUocWA4NAGPmYdKNmQEh8H6iL_4Ik
